/* main.js — adagora.github.io
   Navigation, scroll reveal, contribution graph, shipstream feed.
   All profile content is static HTML generated by scripts/build.js;
   this file only adds behaviour and the two daily data feeds. */

(function () {
  'use strict';

  const $ = (sel, ctx) => (ctx || document).querySelector(sel);
  const $$ = (sel, ctx) => [...(ctx || document).querySelectorAll(sel)];
  const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  const css = (name) => getComputedStyle(document.documentElement).getPropertyValue(name).trim();

  /* ── Mobile nav ── */
  const bar = $('.topbar');
  const toggle = $('.nav-toggle');
  if (toggle) {
    toggle.addEventListener('click', () => {
      const open = bar.classList.toggle('open');
      toggle.setAttribute('aria-expanded', String(open));
    });
    $$('.topnav a').forEach((a) => a.addEventListener('click', () => {
      bar.classList.remove('open');
      toggle.setAttribute('aria-expanded', 'false');
    }));
  }

  /* ── Active nav link ── */
  const navLinks = $$('.topnav a');
  const sections = navLinks.map((a) => $(a.getAttribute('href'))).filter(Boolean);
  function updateActiveNav() {
    const y = window.scrollY + 140;
    let current = '';
    for (const s of sections) if (s.offsetTop <= y) current = '#' + s.id;
    for (const a of navLinks) a.classList.toggle('active', a.getAttribute('href') === current);
  }
  window.addEventListener('scroll', updateActiveNav, { passive: true });
  updateActiveNav();

  /* ── Scroll reveal (content stays visible without JS) ── */
  if ('IntersectionObserver' in window) {
    const io = new IntersectionObserver((entries) => {
      for (const e of entries) if (e.isIntersecting) { e.target.classList.add('in'); io.unobserve(e.target); }
    }, { threshold: 0.08 });
    $$('.section').forEach((el) => { el.classList.add('reveal'); io.observe(el); });
  }

  /* ── Contribution graph ── */
  let statsData = null;

  function renderGraph(canvas, data) {
    const ctx = canvas.getContext('2d');
    if (!ctx) return;
    const W = canvas.clientWidth;
    const H = 130;
    const dpr = window.devicePixelRatio || 1;
    canvas.width = W * dpr;
    canvas.height = H * dpr;
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    ctx.clearRect(0, 0, W, H);

    const muted = css('--muted');
    const colors = ['--g0', '--g1', '--g2', '--g3', '--g4'].map(css);
    const font = '10px "IBM Plex Mono", monospace';

    if (!data || !data.days || Object.keys(data.days).length === 0) {
      ctx.fillStyle = muted;
      ctx.font = font;
      ctx.textAlign = 'center';
      ctx.fillText('Commit data appears after the daily GitHub Action runs', W / 2, H / 2);
      return;
    }

    const cell = 11, gap = 3, step = cell + gap, cols = 53, rows = 7;
    const startX = Math.max(28, (W - cols * step) / 2);
    const today = new Date();
    const start = new Date(today);
    start.setFullYear(start.getFullYear() - 1);
    start.setDate(start.getDate() - start.getDay());
    const levels = [0, 1, 3, 6, Infinity];
    const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

    ctx.fillStyle = muted;
    ctx.font = font;
    ctx.textAlign = 'start';
    for (let c = 0; c < cols; c++) {
      const d = new Date(start); d.setDate(d.getDate() + c * 7);
      const prev = new Date(d); prev.setDate(prev.getDate() - 7);
      if (c === 0 || d.getMonth() !== prev.getMonth()) ctx.fillText(months[d.getMonth()], startX + c * step, 10);
    }
    ctx.textAlign = 'end';
    ['', 'Mon', '', 'Wed', '', 'Fri', ''].forEach((l, r) => { if (l) ctx.fillText(l, startX - 6, 26 + r * step + 4); });

    for (let c = 0; c < cols; c++) {
      for (let r = 0; r < rows; r++) {
        const d = new Date(start); d.setDate(d.getDate() + c * 7 + r);
        if (d > today) continue;
        const count = data.days[d.toISOString().slice(0, 10)] || 0;
        const level = Math.min(4, levels.findIndex((t) => count <= t));
        ctx.fillStyle = colors[level];
        ctx.fillRect(startX + c * step, 18 + r * step, cell, cell);
      }
    }
  }

  function loadStats() {
    const canvas = $('#activity-graph');
    fetch('data/commit-stats.json')
      .then((r) => r.json())
      .then((data) => {
        statsData = data;
        if (canvas) renderGraph(canvas, data);
        if (data.total > 0) {
          const total = data.total.toLocaleString('en-US');
          const el = $('#graph-total');
          if (el) el.innerHTML = `<strong>${total}</strong> commits in the last year`;
          $$('[data-live="commits"]').forEach((n) => { n.textContent = total; });
        }
        const repoCount = data.repoCount ?? (data.repos ? data.repos.length : 0);
        const src = $('#graph-source');
        if (src && repoCount) src.textContent = `across ${repoCount} repositories`;
      })
      .catch(() => canvas && renderGraph(canvas, null));
  }
  loadStats();

  let resizeTimer;
  window.addEventListener('resize', () => {
    clearTimeout(resizeTimer);
    resizeTimer = setTimeout(() => { const c = $('#activity-graph'); if (c && statsData) renderGraph(c, statsData); }, 200);
  });
  if (window.matchMedia) {
    window.matchMedia('(prefers-color-scheme: light)').addEventListener?.('change', () => {
      const c = $('#activity-graph'); if (c && statsData) renderGraph(c, statsData);
    });
  }

  /* ── Shipstream ── */
  function timeAgo(dateStr) {
    const diff = Date.now() - new Date(dateStr).getTime();
    const mins = Math.round(diff / 60000), hours = Math.round(diff / 3600000), days = Math.round(diff / 86400000);
    if (mins < 1) return 'just now';
    if (mins < 60) return `${mins}m ago`;
    if (hours < 24) return `${hours}h ago`;
    if (days === 1) return 'yesterday';
    if (days < 30) return `${days}d ago`;
    if (days < 365) return `${Math.round(days / 30)}mo ago`;
    return `${Math.round(days / 365)}y ago`;
  }

  const ICON_COMMIT = '<svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor" aria-hidden="true"><path d="M11.93 8.5a4.002 4.002 0 0 1-7.86 0H.75a.75.75 0 0 1 0-1.5h3.32a4.002 4.002 0 0 1 7.86 0h3.32a.75.75 0 0 1 0 1.5H11.93zm-3.93-2.5a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3z"/></svg>';
  const ICON_PR = '<svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor" aria-hidden="true"><path d="M1.5 3.25a2.25 2.25 0 1 1 3 2.122v5.256a2.251 2.251 0 1 1-1.5 0V5.372A2.25 2.25 0 0 1 1.5 3.25zm5.677-.177L9.573.677A.25.25 0 0 1 10 .854v2.396h.775c1.766 0 3.225 1.312 3.225 2.93v3.188a2.251 2.251 0 1 1-1.5 0V6.18c0-.552-.492-.854-1.225-.854H10v2.396a.25.25 0 0 1-.427.177L7.177 5.427a.25.25 0 0 1 0-.354z"/></svg>';

  function renderShipstream(data) {
    const feed = $('#shipstream-feed');
    if (!feed) return;
    if (!data || !data.items || data.items.length === 0) {
      feed.innerHTML = '<div class="shipstream-empty">No recent activity yet.</div>';
      return;
    }
    const seen = new Set();
    const items = data.items.filter((i) => {
      const key = i.sha || `${i.title || i.message}@${i.date}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    });
    feed.innerHTML = items.map((item) => {
      const isPr = item.type === 'pr';
      const text = esc(isPr ? item.title : item.message);
      const title = item.url && !item.private ? `<a href="${esc(item.url)}" target="_blank" rel="noopener">${text}</a>` : text;
      const repo = esc(String(item.repo || '').replace(/^adagora\//, ''));
      return `<div class="shipstream-item">
        <span class="shipstream-icon ${isPr ? 'pr' : 'commit'}">${isPr ? ICON_PR : ICON_COMMIT}</span>
        <div>
          <div class="shipstream-title">${title}</div>
          <div class="shipstream-meta">
            <span>${repo}</span>
            ${isPr ? '<span class="shipstream-badge merged">merged</span>' : ''}
            ${item.private ? '<span class="shipstream-badge private">private repo</span>' : ''}
            <span>${timeAgo(item.date)}</span>
          </div>
        </div>
      </div>`;
    }).join('');
  }

  fetch('data/recent-activity.json')
    .then((r) => r.json())
    .then((data) => {
      renderShipstream(data);
      const footer = $('#shipstream-footer');
      if (footer && data.generated) {
        const d = new Date(data.generated);
        footer.textContent = `Updated ${d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })} by a GitHub Action`;
      }
    })
    .catch(() => {
      const feed = $('#shipstream-feed');
      if (feed) feed.innerHTML = '<div class="shipstream-empty">Could not load the activity feed.</div>';
    });
})();
